# Use native Wayland through Ozone.
--ozone-platform=wayland

# Use Chromium's VA-API path through ANGLE/OpenGL.
--use-gl=angle
--use-angle=gl
--ignore-gpu-blocklist
--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL
